- hosts: production 
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt -y update && apt install -y python-minimal
      sudo: yes
    - setup:
  vars:
    app_name: state_2c_geonode
    github_user: CmdrKerfy 
    server_name: 34.207.144.71 
    repo_name: 2C-GeoNode
    deploy_user: ubuntu
  roles:
     - { role: GeoNode.geonode }
